### PR TITLE
Update src/jquery.poshytip.js

### PR DESCRIPTION
**Pull request by brendanheywood**
I've had a particularly complex use case where the refresh animation cause some repetitive animation, so I've added an option to change or remove the refreshAniDuration

### CODE REVIEW

**Comment by an6r** [comment]
Hi! It's a very useful enhancement. I need this option very much!!!

**Comment by vadikom** [comment]
Thanks and sorry it took so long to reply (I've been very busy lately)! I will now merge it.

**Comment by an6r** [comment]
Thanks for merge. But what is about min version (compressed one)?
Or, could you tell, please, what compiler do you use to make it?

**Comment by vadikom** [comment]
Just updated the min version and the docs too! Thanks!

**Comment by vadikom** [comment]
I don't use a compiler for now, maybe I should..

**Comment by vadikom** [comment]
Actually, I meant I don't use an automated build system for the source - otherwise I use YUI compressor. Here's an online version http://www.refresh-sf.com/yui/

**Pull request merged**
